#include "wnh_filesync_control.h"


void wnh_filesync_control::ues_instructions() //使用说明
{
    cout << WNH_COLOR_BOLDWHITE << "┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│                                                    " << WNH_COLOR_BOLDMAGENTA << PROGRAM_NAME << " 服务端使用说明" << WNH_COLOR_BOLDWHITE << "                                                  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "      启动参数      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << " filesync server 配置文件路径 PID文件路径 是否root限定 日志等级                                                " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "  范例 1 (缺省方式) " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << " filesync server filesync.conf " << WNH_COLOR_RESET << "                                                                                " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "  范例 2 (完整方式) " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << " filesync server filesync.conf filesync_server.pid \"limit root\" WNH_INFO_XS                                    " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│                                                    " << WNH_COLOR_BOLDMAGENTA << PROGRAM_NAME << " 客户端使用说明" << WNH_COLOR_BOLDWHITE << "                                                  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "      启动参数      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << " filesync client 服务端IP 服务端PORT PID文件路径 是否root限定 日志等级                                         " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "  范例 1 (缺省方式) " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << " filesync client 127.0.0.1 10086 " << WNH_COLOR_RESET << "                                                                              " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "  范例 2 (完整方式) " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << " filesync client 127.0.0.1 10086 filesync_client.pid \"limit root\" WNH_INFO_XS                                  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│                                                    " << WNH_COLOR_BOLDMAGENTA << PROGRAM_NAME << " 控制端使用说明" << WNH_COLOR_BOLDWHITE << "                                                  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "      启动参数      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << " filesync control 使用参数 服务端IP 服务端PORT PID文件路径 是否root限定 日志等级                               " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "  范例 1 (缺省方式) " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << " filesync                                                                                        " << WNH_COLOR_RESET << "(显示使用帮助)" << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "  范例 2 (缺省方式) " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << " filesync list                                                                             " << WNH_COLOR_RESET << "(显示控制端使用列表)" << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "  范例 3 (完整方式) " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << " filesync control list 127.0.0.1 10086 filesync_control.pid \"no limit root\" WNH_INFO_XS                        " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "├────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDGREEN << "  说明: 如果系统参数配置足够完整的话, 可以缺省至直接执行 " << WNH_COLOR_BOLDRED << "filesync" << WNH_COLOR_BOLDGREEN << " 启动程序.                                                         " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDGREEN << "        缺省的参数从系统变量中获取,若系统变量也不存在将使用程序默认值.                                                              " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
	cout << WNH_COLOR_BOLDWHITE << "└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘" << WNH_COLOR_RESET << endl;
}

void wnh_filesync_control::control_use_instructions() //控制端使用说明
{
	cout << WNH_COLOR_BOLDWHITE << "┌──────┬───────────────────────┬────────────────────────────────────────┬────────────────────────────────────────────────────────────┐" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << " 序号 " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN  << "         参数          " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "                  说明                  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "                         使用范例                           " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├──────┼───────────────────────┼────────────────────────────────────────┼─────────────────────────┬──────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  1   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "       show list       " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "            显示使用命令列表            " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync show 1     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "      filesync \"show list\"        " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├──────┼───────────────────────┼────────────────────────────────────────┼─────────────────────────┼──────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  2   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "  show server client   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "         显示服务端和客户端状态         " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync show 2     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "  filesync \"show server client\"   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├──────┼───────────────────────┼────────────────────────────────────────┼─────────────────────────┼──────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  3   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << " show server client s  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "       实时显示服务端和客户端状态       " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync show 3     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << " filesync \"show server client s\"  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├──────┼───────────────────────┼────────────────────────────────────────┼─────────────────────────┼──────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  4   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "      show server      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "             显示服务端列表             " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync show 4     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync \"show server\"       " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├──────┼───────────────────────┼────────────────────────────────────────┼─────────────────────────┼──────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  5   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     show server s     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "           实时显示服务端列表           " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync show 5     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "    filesync \"show server s\"      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├──────┼───────────────────────┼────────────────────────────────────────┼─────────────────────────┼──────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  6   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "      show client      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "             显示客户端列表             " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync show 6     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync \"show client\"       " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "├──────┼───────────────────────┼────────────────────────────────────────┼─────────────────────────┼──────────────────────────────────┤" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  7   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     show client s     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "           实时显示客户端列表           " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync show 7     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "    filesync \"show client s\"      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_RESET << endl;
    cout << WNH_COLOR_BOLDWHITE << "└──────┴───────────────────────┴────────────────────────────────────────┴─────────────────────────┴──────────────────────────────────┘" << WNH_COLOR_RESET << endl;
}