#include "wnh_filesync_control.h"


void wnh_filesync_control::ues_instructions() //使用说明
{
	cout << WNH_COLOR_BOLDWHITE << "┌──────┬──────────────────┬────────────────────────────────────────┬─────────────────────────────────────────────────────────────────┐" << endl;
    cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << " 序号 " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "       参数       " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "                  说明                  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "                            使用范例                             " << WNH_COLOR_BOLDWHITE << "│" << endl;
	cout << WNH_COLOR_BOLDWHITE << "├──────┼──────────────────┼────────────────────────────────────────┼────────────────────────────┬────────────────────────────────────┤" << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  1   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "       list       " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "            显示使用命令列表            " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync control 1     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "       filesync control list        " << WNH_COLOR_BOLDWHITE << "│" << endl;
	cout << WNH_COLOR_BOLDWHITE << "├──────┼──────────────────┼────────────────────────────────────────┼────────────────────────────┼────────────────────────────────────┤" << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  2   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "  server client   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "         显示服务端和客户端状态         " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync control 2     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "  filesync control \"server client\"  " << WNH_COLOR_BOLDWHITE << "│" << endl;
	cout << WNH_COLOR_BOLDWHITE << "├──────┼──────────────────┼────────────────────────────────────────┼────────────────────────────┼────────────────────────────────────┤" << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  3   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << " server client s  " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "       实时显示服务端和客户端状态       " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync control 3     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << " filesync control \"server client s\" " << WNH_COLOR_BOLDWHITE << "│" << endl;
	cout << WNH_COLOR_BOLDWHITE << "├──────┼──────────────────┼────────────────────────────────────────┼────────────────────────────┼────────────────────────────────────┤" << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  4   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "      server      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "             显示服务端列表             " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync control 4     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "      filesync control server       " << WNH_COLOR_BOLDWHITE << "│" << endl;
	cout << WNH_COLOR_BOLDWHITE << "├──────┼──────────────────┼────────────────────────────────────────┼────────────────────────────┼────────────────────────────────────┤" << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  5   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     server s     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "           实时显示服务端列表           " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync control 5     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "    filesync control \"server s\"     " << WNH_COLOR_BOLDWHITE << "│" << endl;
	cout << WNH_COLOR_BOLDWHITE << "├──────┼──────────────────┼────────────────────────────────────────┼────────────────────────────┼────────────────────────────────────┤" << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  6   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "      client      " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "             显示客户端列表             " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync control 6     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "      filesync control client       " << WNH_COLOR_BOLDWHITE << "│" << endl;
	cout << WNH_COLOR_BOLDWHITE << "├──────┼──────────────────┼────────────────────────────────────────┼────────────────────────────┼────────────────────────────────────┤" << endl;
	cout << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "  7   " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     client s     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDRED << "           实时显示客户端列表           " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDYELLOW << "     filesync control 7     " << WNH_COLOR_BOLDWHITE << "│" << WNH_COLOR_BOLDCYAN << "    filesync control \"client s\"     " << WNH_COLOR_BOLDWHITE << "│" << endl;
	cout << WNH_COLOR_BOLDWHITE << "└──────┴──────────────────┴────────────────────────────────────────┴────────────────────────────┴────────────────────────────────────┘" << endl;
}
